// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvfwrsatlyvxktvprptf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2Zndyc2F0bHl2eGt0dnBycHRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyODM1NzQsImV4cCI6MjA5Nzg1OTU3NH0.aKvOASmzQYpq0AmSSVapQUCMX4z1kmc8mZIxGI6XFEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});